---
broker: 'redis://123456@10.70.19.170:6379/7'
default_queue: machinery_tasks
#  binding_key: binding_key
cycle_queue: cycle_tasks
monitor_worker_queue: monitor_worker_queue
monitor_server_queue: monitor_server_queue
result_backend: 'redis://123456@10.70.19.170:6379/8'
results_expire_in: 123456
#amqp:
#  binding_key: binding_key
#  exchange: exchange
#  exchange_type: exchange_type
#  prefetch_count: 123
#  queue_declare_args:
#    x-max-priority: 10
#  queue_binding_args:
#    image-type: png
#    x-match: any
