---
broker: 'redis://localhost:6379/10'
default_queue: machinery_tasks
cycle_queue: cycle_tasks
monitor_queue: machinery_monitor_queue
result_backend: 'redis://localhost:6379/9'
results_expire_in: 123456
#amqp:
#  binding_key: binding_key
#  exchange: exchange
#  exchange_type: exchange_type
#  prefetch_count: 123
#  queue_declare_args:
#    x-max-priority: 10
#  queue_binding_args:
#    image-type: png
#    x-match: any
